testimonials:
  - date: "2019-07-26" 
    quote: "Chad was amazing, please send more teachers like him" 
    stars: 5
    classid: napya
    name: Arfonze Prajorca Sr
  - date: "2019-07-26" 
    quote: "Sam is amazing, please send more teachers like him" 
    stars: 5
    classid: napya
    name: Arfonze Prajorca Jr.
  - date: "2019-07-26" 
    quote: "There needs to be LazyBoy chairs and mixed drinks!" 
    stars: 1
    classid: napya
    name: Arfonze Griper the 3rd
  - date: "2019-07-26" 
    quote: "Billy was amazing, please send more teachers like her" 
    stars: 5
    classid: napya
    name: Arfonze Prajorca the 4th
