id: Bulletproof 
title: Writing Bulletproof Code
date: 2019-04-01
weight: "50"
author: Andy Structible 
category: Programming
video-link: https://youtu.be/h-WfQrTvOMk
intro: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
---
Cool stuff that would interest the general crowd
