---
id: stars
Title: Rotten Stars
Date: 02-12-2018
Weight: "5"
Author: Sean
----


I hope that my title does not throw readers off, nor do I hope that the introduction deter readers from glancing and especially, nor do I want the ratings from a few lousy tippers to have a stronghold on whether or not a potential customer purchases my product. 

Do I just say screw the new incoming generation and not do stars/eggs/hearts/etc/etc/etc/etc(keep going with this with examples). 

Can I rightfully, and ethically delete those negative reviews? Sure can because I am bias.. I mean unbias.



I was looking at pc cases
tracy conversation. don't even go to the second page anymore. if something even has 4/5 stars I question but don't look at the reviews, i move on to look for higher rated reviews. Also, I then look to see (I forget at which point) how many reviews there actually are, maybe to see if reviews are real or not or if there are idiots reviewing.
