---
id: pyfna 
course-title: Python for Network Automation
tags: 
  -  programming
  -  networking
stars: 47
duration:
  hours: 35 
  days: 5
audience: "For individuals who want to use Python to automate network tasks, increasing implementation and decreasing deployment times"
prereqs: 
  -  Python Basics
postreqs: 
  -  Network Automation with Python and Ansible
testimonials:
  - quote: "labs worked well and were very interesting."
    stars: 5
  - quote: "Zach is wonderful and very knowledgeable!"
    stars: 5
video-link: "https://www.youtube.com/embed/gwSvV5KM3hg?rel=0;autoplay=1"
web-url: "https://alta3.com/courses/pyfna"
has-labs: true
has-videos: true
has-slides: true
filename: courses/pyfna.json
price:
  public:
    price-tags:
      - id: priceinfo-public-single-student 
        description: Face to face training for 1 student
        price: 800000
        available: yes
        includes: 
        - item : has-video-true
          description: Includes video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
          description: Does not include labs
  private:
    price-tags:
      - id: priceinfo-private-base8
        description: face to face training for up to 8 students
        price: 850000
        available: yes
        includes: 
        - item : has-video-true
          description: Includes video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
          description: Does not include labs
      - id: priceinfo-private-plus1-to-base8
        description: Add one additional student base8 
        price: 50000
        available: yes
        includes: 
         - item : plus1
           description: Includes same features as base 8
  self-paced:
    price-tags:
      - id: priceinfo-selfpaced-singlestudent 
        description: Self Paced Training
        price: 250000
        available: yes
        includes: 
        - item : has-video-true
          description: Includes video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
          description: Does not include labs
      - id: priceinfo-selfpaced-sixpack
        description: Package price for six self=paced students
        price: 500000
        available: yes
        includes: 
        - item : has-video-true
          description: Includes video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
          description: Does not include labs
  extend-lms-access:
    price-tags:
      - id: priceinfo-extendaccess-lab-one-month
        description: Extend your lab access for one month
        price: 5000
        available: no
      - id: priceinfo-extendaccess-lab-one-year
        description: Extend your lab access for one month
        price: 50000
        available: no
  book:
    price-tags:
      - id: priceinfo-book-paper 
        description: Paper Student Manual 
        price-desc: 
        price: 850000
        available: yes
        includes: 
        - item: has-video-false
          description: Does not include video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
          description: Does not include labs
      - id: priceinfo-book-online 
        description: Paper Student Manual 
        price-desc: 
        price: 450000
        available: yes
        includes: 
        - item : has-video-false
          description: Does not include video
        - item : has-book-true
          description: Includes on-line book
        - item : has-labs-false
overview: This is a demo and hands on driven course for learning Python for Network Automation, taught by a network and python professional. Maximize your networking skill set by learning to script solutions to tedious and complex tasks. Use Python to interact with APIs, opening Telnet and SSH sessions, work with files and popular data structures, automate filling out web forms, and learn to interact with switches and routers across the most popular network vendors. Class is a combination of lecture, demonstration, and hands-on labs. Students are invited to share their own relevant Python and Ansible scripts with the instructor to ensure class subjects are as relevant as possible.
chapters:
-   guid: 1db9b07e-83e0-4d22-84a9-7cb1a3258b38
    subchapters:
    -   questions: []
        slides:
        - {guid: 59bf5b5a-344e-456e-904c-0a5d53aa0c99, index: 3, title: Python Socket
                Module - Ports}
        - {guid: 8df7ccf4-2aa8-4a67-a843-830199bf1b72, index: 4, title: Python Socket
                Module - Sockets}
        title: Contents
    title: Sockets and Networking
-   guid: b08a3d5e-4e56-4155-9fd6-4f885ec0cc19
    subchapters:
    -   questions: []
        slides:
        - {guid: 5f6c8146-222d-4a56-9fc8-05f4b7498a58, index: 6, title: Network Automation
                Transactions}
        - {guid: c8cf5ad1-417c-49ff-879c-df840e7da801, index: 7, title: NAPALM}
        - {guid: b7c8a7e3-ca83-4e9d-a776-8f84fa0cf7e7, index: 8, title: How Napalm
                works}
        - {guid: 4e32f526-5a4a-4597-8bef-886e88f20054, index: 9, title: Napalm Installation}
        - {guid: 227dd5b6-f829-4487-8e39-c827d061c3c5, index: 10, title: Load / Replace
                Config with Napalm}
        - {guid: cc09679d-0c04-4d0d-83dd-ad6f8615d1a3, index: 11, title: Getting a
                driver}
        - {guid: 49ed7817-348d-443b-ad90-760eaf2a19b4, index: 12, title: Connecting
                to the device}
        - {guid: c11eaba8-30a2-42da-ad24-cb001c9df721, index: 13, title: Replacing
                the Configuration}
        - {guid: 2f713fe3-3be9-4e91-8564-4c686bf1a50e, index: 14, title: Disconnect}
        - {guid: 6aed4e97-a578-45a4-9086-e4a0cb2bb473, index: 15, title: Context Manager}
        - {guid: b7efe692-c529-43d8-b417-70fb9c62a113, index: 16, title: NAPALM Methods}
        - {guid: f3db6910-819e-46cd-b694-2c661093c1f0, index: 17, title: NAPALM Merging
                Configuration}
        - {guid: ffcbc7ef-3127-443e-961e-8fba16a24844, index: 18, title: NAPALM -
                Disconnect}
        title: Contents
    title: NAPALM
-   guid: db7d5d09-c670-46da-b2cb-24350e38e61d
    subchapters:
    -   questions: []
        slides:
        - {guid: d187203f-9f75-43bd-9209-913797e0345b, index: 20, title: Paramiko
                Overview}
        - {guid: 19dc4822-dea9-4871-94dc-90bf4d1be100, index: 21, title: Installing
                Paramikio}
        - {guid: 1f291146-c5ac-44b5-be88-2241dbee1fd0, index: 22, title: Paramiko
                to Router Overview}
        - {guid: 9a12dab4-8cd1-4cd0-9380-8d96fdef8ee1, index: 23, title: Paramiko
                to Router Overview (continued)}
        - {guid: f52a18d6-7e5e-4925-82f9-160836fde596, index: 24, title: Paramiko
                to Router Overview (continued)}
        - {guid: d137787e-1eed-49b6-a0a0-9f5d63511380, index: 25, title: Paramiko
                to Router Overview (continued)}
        - {guid: 3e163207-2570-47d8-8118-852dd1789ea6, index: 26, title: "Paramiko\
                \ to Router \u2013 Python Script (1 of 4) "}
        - {guid: de0aceb2-006b-407d-bbbd-918d86ff6a79, index: 27, title: "Paramiko\
                \ to Router \u2013 Python Script (2 of 4)"}
        - {guid: 74f6205d-189f-4ba0-897c-33ba38325a4a, index: 28, title: "Paramiko\
                \ to Router \u2013 Python Script (3 of 4)"}
        - {guid: dfe79826-bdad-4ec0-8661-ae8804e82e9f, index: 29, title: "Paramiko\
                \ to Router \u2013 Python Script (4 of 4)"}
        - {guid: 03c49e5f-f5c0-405a-8b4d-426c2841c099, index: 30, title: "Paramiko\
                \ to Router \u2013 Python Script - Results"}
        - {guid: 4e3bc305-6b5e-4708-9210-75215f9b9b6f, index: 31, title: "Case Study\
                \ \u2013 Paramiko Automation \u2013 Overview "}
        - {guid: 19c5dbc9-1a93-4ee2-8fd0-0170ebadf5a6, index: 32, title: "Case Study\
                \ \u2013 Paramiko Automation"}
        - {guid: dafa5706-4566-4ac7-a4c3-223931cf64a1, index: 33, title: "Case Study\
                \ \u2013 Paramiko Automation"}
        - {guid: 576d4830-5821-47f0-ae3b-b890713e347f, index: 34, title: "Case Study\
                \ \u2013 Paramiko Automation"}
        title: Contents
    title: Paramiko
-   guid: f3cc1750-caa2-4146-9ee4-6f317fad81fc
    subchapters:
    -   questions: []
        slides:
        - {guid: 9ec6dcc7-bbd1-4d01-add4-6eb7f661d187, index: 36, title: Netmiko Overview}
        - {guid: ef6554b4-7340-47db-9ac9-00e290159cef, index: 37, title: Netmiko Class
                Overview}
        - {guid: a45005e4-75f6-4e4f-92f0-3e790ad13819, index: 38, title: Netmiko Platform
                Support}
        - {guid: db4c6f69-1399-4dd1-9fdc-86cadea3997c, index: 39, title: "A simple\
                \ SSH session to a Router \u2013 Setup"}
        - {guid: bf757749-55cf-44f3-a0d0-6683a49c68c6, index: 40, title: "A simple\
                \ SSH session to a Router \u2013 Connect"}
        - {guid: 36c2ce98-21c4-4bcb-9bf9-949d462a99ac, index: 41, title: "A simple\
                \ SSH session to a Router \u2013 Find Prompt"}
        - {guid: e4ce4b19-1fd8-4cfb-be6d-69076bbf7fa8, index: 42, title: "A simple\
                \ SSH session to a Router \u2013 Send Command (show ip int br)"}
        - {guid: 0a230f8e-c874-4b5e-8a89-86541adb2891, index: 43, title: "A simple\
                \ SSH session to a Router \u2013 Send Command (show run)"}
        - {guid: 1532a7c4-5820-4468-ac9b-e0df8b1f61df, index: 44, title: "A simple\
                \ SSH session to a Router \u2013 Send Commands (with lists)"}
        - {guid: 2eb33b55-f47d-468f-adc5-c951c94d5cee, index: 45, title: Available
                Netmiko Methods}
        - {guid: 75ca70b9-2f49-4e7b-ae70-639b04cc711d, index: 46, title: Issuing commands
                on multiple devices}
        - {guid: 9191f434-0e35-45f3-af00-be244e42c1f7, index: 47, title: Issuing commands
                on multiple devices (continued)}
        - {guid: 1830937c-fca6-4e17-8387-8e639b13cebc, index: 48, title: Issuing commands
                on multiple devices (continued)}
        - {guid: 2aabe094-1ae5-412e-a9cc-d713f2895566, index: 49, title: "Issuing\
                \ commands on multiple devices \u2013 Output"}
        - {guid: 8ee152a3-a7f0-4e86-8e70-c1d408fa93aa, index: 50, title: "Issuing\
                \ commands on multiple devices \u2013 Output (continued)"}
        - {guid: 1559164e-4ea3-444f-b183-857ddd4906fc, index: 51, title: "Issuing\
                \ commands on multiple devices \u2013 Output (continued)"}
        - {guid: 547494ce-2e97-4457-b987-7e635029cebe, index: 52, title: "Issuing\
                \ commands on multiple devices \u2013 Output (continued)"}
        - {guid: 9050c159-2d8d-42f5-82f5-f007410b49c7, index: 53, title: "Case Study\
                \ \u2013 Switch Automation \u2013 Overview "}
        - {guid: 7a246df8-70d0-4b31-b3ca-9bca9117088b, index: 54, title: "Case Study\
                \ \u2013 Switch Automation"}
        - {guid: 4c398944-64e9-43ee-8fe6-2c1d33c23215, index: 55, title: "Case Study\
                \ \u2013 Switch Automation"}
        - {guid: fc3e5eaa-dfa2-43c6-bbe5-1d70a0cd69c1, index: 56, title: "Case Study\
                \ \u2013 Switch Automation"}
        - {guid: 02af0cdc-527f-443b-bbe5-d5c2507c084d, index: 57, title: "Case Study\
                \ \u2013 Switch Automation"}
        - {guid: 9b2f5016-d20f-4b8b-8c88-31d6a59147ac, index: 58, title: "Case Study\
                \ \u2013 Switch Automation"}
        title: Contents
    title: Netmiko
